### ISSUE TITLE
"easy_pwait" exampled in README is wrong and misleading

### ISSUE THREAD

**Issue by UnitedMarsupials-zz** [diazona/pwait#2]
Relying on periodic polling is a bad idea in general for a number of reasons:

- With time interval too short, you continuously chew up the system's resources (CPU and RAM) as process constantly wakes up and can not be paged-out even on a busy system
- With time interval too long, there may be a significant delay before you notice the process is gone

What makes this particular example especially dangerous is that, once in a while, a _new_ process may appear with the same PID during the 5 seconds between the checks, and your `easy_pwait` will never realize it.

The C-code you have does not have any of these problems -- do not devalue it :-)

**Comment by diazona** [comment]
I considered exactly these issues when writing the README. In most cases, I don't believe these problems are relevant because

- it's not important to know exactly when the process ends, so the polling time can safely be set to a relatively large value
- the small risk that a new process will be created with the same PID within a few seconds is entirely tolerable

In those cases, I don't think it makes sense to recommend installing a new program (i.e. pwait) when a simple shell function does the job perfectly well. In the relatively few situations where it is important to know exactly when a process ends and important to eliminate the chance of another process "stealing" the PID, I think users will know this, and in those cases they can use the C code.

If the evidence shows that the shell function is causing more trouble than it's worth, then I'm certainly open to changing the README.

**Comment by UnitedMarsupials-zz** [comment]
I'm curious, what would you consider to be suitable "evidence" - even in theory?

**Comment by diazona** [comment]
I'd be looking for feedback from a significant number (maybe 5-ish?) of users of the program confirming that this has been a problem for them, and that they were misled by the existing explanation.

I should be clear that I'm open to changing the way the script is presented, or adding a section in the README and/or wiki that explains it in more detail, to make it more clear what it does and doesn't do. But I would want to see evidence from users before entirely removing the recommendation to use the shell script.

(Sorry for the delay, I was busy last week)

**Comment by UnitedMarsupials-zz** [comment]
Things that work 99% of the time are the hardest to debug... At least, you should've cooked something up with inotify waiting for the `/proc/PID` Instead. The sleep-check polling is _just wrong_.
